CREATE TABLE "DIM_VENDEDOR"
    ("SK_VENDEDOR" NUMBER NOT NULL ENABLE,
    "COD_VENDEDOR" VARCHAR2(10 BYTE),
    "DES_VENDEDOR" VARCHAR2 (200 BYTE),
    CONSTRAINT "DIM_VENDED_DIM_KEY_PK" PRIMARY KEY ("SK_VENDEDOR"));

CREATE INDEX "NVENDED_IDX" ON "DIM_VENDEDOR" ("COD_VENDEDOR");
