CREATE TABLE "DIM_DEPARTAMENTO" (
    "SK_DEPARTAMENTO"    NUMBER NOT NULL ENABLE,
    "COD_DEPARTAMENTO"   VARCHAR2(10 BYTE),
    "DES_DEPARTAMENTO"   VARCHAR2(200 BYTE),
    "DTC_INICIO"         DATE,
    "DTC_FIM"            DATE,
    CONSTRAINT "DIM_DEPARTAMENTO_PK" PRIMARY KEY ( "SK_DEPARTAMENTO" ) ENABLE
);

CREATE INDEX "DEPART_IDX" ON "DIM_DEPARTAMENTO" ("COD_DEPARTAMENTO");