CREATE TABLE "DIM_PRODUTO"
    ("SK_PRODUTO" NUMBER NOT NULL ENABLE,
    "COD_PRODUTO" VARCHAR2(10 BYTE),
    "DES_PRODUTO" VARCHAR2 (200 BYTE),
    "DTC_INICIO" DATE,
    "DTC_FIM" DATE,
    CONSTRAINT "DIM_PRODUTO_DIM_KEY_PK" PRIMARY KEY ("SK_PRODUTO"));

CREATE INDEX "NPRODUTO_IDX" ON "DIM_PRODUTO" ("COD_PRODUTO");

