"UPDATE DIM_PRODUTO PROD
SET PROD.DTC_INICIO=TO_DATE('01/01/1900 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
WHERE EXISTS 
    (SELECT PROD2.COD_PRODUTO, COUNT(*) 
    FROM DIM_PRODUTO PROD2
    WHERE PROD2.COD_PRODUTO = PROD.COD_PRODUTO
    GROUP BY PROD2.COD_PRODUTO
    HAVING (COUNT(*)=1))"