"UPDATE DIM_DEPARTAMENTO DEP
SET DEP.DTC_INICIO=TO_DATE('01/01/1900 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
WHERE EXISTS 
    (SELECT COD_DEPARTAMENTO, COUNT(*) 
    FROM DIM_DEPARTAMENTO DEP2
    WHERE DEP2.COD_DEPARTAMENTO = DEP.COD_DEPARTAMENTO
    GROUP BY COD_DEPARTAMENTO
    HAVING (COUNT(*)=1))"